name: release

on:
  push:
    branches:
      - main
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install build reqs
      run: ./helper.sh reqs
    - name: test
      run: ./helper.sh test
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: get timestamp
      id: timestamp
      run: echo "::set-output name=ts::$(date +'%y%m%d%H%M%S')"
    - name: install build reqs
      run: ./helper.sh reqs
    - name: build
      run: ./helper.sh build
    - name: publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
